Handle inconsistant syntax of sqlite3 .schema output
While dumping SQLite database with schema version 120, the script
returned this error:

    Error: near ";": syntax error
    Error: near line 2: near ";": syntax error

It was caused by the .schema sqlite command for table 'tasks'. Instead
of being formated that way:

    CREATE TABLE <table> (

The 'tasks' table had its ( on its own line:

    CREATE TABLE IF NOT EXISTS "tasks"
            (

This PR add a sed regexp to handle this case.